-- Otelier Backend – PostgreSQL Schema
-- Reflects EF Core migrations: InitialCreate + AddLocalJwtUsers
-- Run this script manually if you prefer not to use "dotnet ef database update"

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Hotels
CREATE TABLE IF NOT EXISTS "Hotels" (
    "Id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL
);

-- Bookings
CREATE TABLE IF NOT EXISTS "Bookings" (
    "BookingId"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HotelId"       integer NOT NULL,
    "GuestName"     character varying(120) NOT NULL,
    "CheckInDate"   timestamp with time zone NOT NULL,
    "CheckOutDate"  timestamp with time zone NOT NULL,
    "CreatedBy"     character varying(100) NOT NULL,
    CONSTRAINT "FK_Bookings_Hotels_HotelId"
        FOREIGN KEY ("HotelId") REFERENCES "Hotels" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Bookings_HotelId_CheckInDate_CheckOutDate"
    ON "Bookings" ("HotelId", "CheckInDate", "CheckOutDate");

-- Users (local JWT authentication)
CREATE TABLE IF NOT EXISTS "Users" (
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName"             character varying(100) NOT NULL,
    "NormalizedUserName"   character varying(100) NOT NULL,
    "PasswordHash"         character varying(512) NOT NULL,
    "Role"                 character varying(30)  NOT NULL,
    "IsActive"             boolean NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_NormalizedUserName"
    ON "Users" ("NormalizedUserName");

-- Seed demo hotels (matches AppDbInitializer)
INSERT INTO "Hotels" ("Name") VALUES
    ('Grand Budapest Hotel'),
    ('The Overlook Hotel'),
    ('Fawlty Towers')
ON CONFLICT DO NOTHING;
